name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 00 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SYMBOL_VERSION: "1"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Update statistics"
          SHOW_TOTAL_CODE_TIME: "False"
          
